#!/opt/homebrew/bin/bash
option="eventsToday"
brew_prefix="$(/opt/homebrew/bin/brew --prefix)"
ical_buddy="/opt/homebrew/bin/icalBuddy"

if [ -e ${brew_prefix}/opt/gnu-sed/libexec/gnubin/sed ]; then
    SED=${brew_prefix}/opt/gnu-sed/libexec/gnubin/sed
else
    SED=${brew_prefix}/opt/gnu-sed/libexec/gnubin/sed
fi

AWK=${brew_prefix}/bin/awk

if [ -n "$1" ]; then
    option="eventsFrom:$1 to:$1"
fi

${ical_buddy} -b '' -npn -nc -ps "/ | /" -nrd -eep "notes,attendees,url" ${option} | \
    ${AWK} -F\| '
{
    if (NF>2) {
        if (index($3, "at") != 0) {
            # This is needed when eventsFrom is used, because it insists on always adding the date.
            gsub(/[0-9]*[0-9] [A-Z][a-z][a-z] [0-9]*[0-9][0-9][0-9] at /,"",$3);
        }
        if (match($3, /[0-9]*[0-9] [A-Z][a-z][a-z] [0-9]*[0-9][0-9][0-9]/) != 0) {
            # This is needed when eventsFrom is used, because it insists on always adding the date.
            gsub(/[0-9]*[0-9] [A-Z][a-z][a-z] [0-9]*[0-9][0-9][0-9]/,"00:00-23:59",$3);
        }
        gsub(/ /,"",$3);
        printf("- `%s`  %s %s\n", $3, $1, $2);
    } else if (NF==1) {
        printf("- %s\n", $1);
    } else {
        if (index($2, "at") != 0) {
            # This is needed when eventsFrom is used, because it insists on always adding the date.
            gsub(/[0-9]*[0-9] [A-Z][a-z][a-z] [0-9]*[0-9][0-9][0-9] at /,"",$2);
        }
        if (match($2, /[0-9]*[0-9] [A-Z][a-z][a-z] [0-9]*[0-9][0-9][0-9]/) != 0) {
            # This is needed when eventsFrom is used, because it insists on always adding the date.
            gsub(/[0-9]*[0-9] [A-Z][a-z][a-z] [0-9]*[0-9][0-9][0-9]/,"00:00-23:59",$2);
        }
        gsub(/ /,"",$2);
        printf("- `%s`  %s\n", $2, $1);
    }
}
' | ${SED} 's/\(https:\/\/[^ ]*\)/[zoom](\1)/' | ${SED} 's/[ ]*Microsoft Teams Meeting[ ]*$//'
