#!/usr/local/bin/bash
/usr/local/bin/icalBuddyFixed -b '' -npn -nc -ps "/ | /" -eep "notes,attendees,url" eventsToday | \
    /usr/local/bin/awk -F\| '
{
    if (NF>2) {
        gsub(/ /,"",$3);
        printf("- `%s`  %s %s\n", $3, $1, $2);
    } else if (NF==1) {
        printf("- %s\n", $1);
    } else {
        gsub(/ /,"",$2);
        printf("- `%s`  %s\n", $2, $1);
    }
}
' | /usr/local/opt/gnu-sed/libexec/gnubin/sed 's/\(https:\/\/[^ ]*\)/[zoom](\1)/'
